cloud:
    project: "<YOUR_PROJECT_ID>"
    storage:
        name: "audio-data"
        backend: "local"
        local_dir: "tmp"
    database:
        backend: "local"
        filepath: "tmp/database-file.json"
        mode: "a"
oauth:
    google:
        client_id: "abc"
        client_secret: "xyz"
    spotify:
        client_id: "abc"
        client_secret: "xyz"
annotator:
    static_folder: "../audio-annotator/static"