google:
  client_id: "abc"
  client_secret: "xyz"
spotify:
  client_id: "abc"
  client_secret: "xyz"
twitter:
  client_id: "abc"
  client_secret: "xyz"
facebook:
  client_id: "abc"
  client_secret: "xyz"