# Necessary for AppEngine deployment.
# First, install deps into the lib directory
#   $ pip install .[appengine] -t lib

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: appengine_dev.app

libraries:
- name: ssl
  version: latest

skip_files:
- google-cloud-sdk
- lib/gapic*
- lib/gunicorn*
- lib/grpc*
- lib/google*
- ^.*\.pyc$
